- project:
    name: rcarrillocruz-org/zuul-tested-repo
    check:
      jobs:
          #- noop
        - hello-world

- job:
    name: hello-world
    run: playbooks/hello-world/run.yaml
    nodeset: []
